import type { Severity, SignalCategory } from "@/lib/types";

export interface SignalPattern {
  id: string;
  category: SignalCategory;
  severity: Severity;
  title: string;
  phrases: string[];
  explanation: string;
}

/**
 * Deterministic scam indicators.
 * Detection logic lives here — never inside an AI prompt.
 */
export const SIGNAL_PATTERNS: SignalPattern[] = [
  {
    id: "urgency_deadline",
    category: "urgency",
    severity: "medium",
    title: "Urgency / deadline pressure",
    phrases: [
      "immediately",
      "urgent",
      "urgently",
      "act now",
      "asap",
      "right away",
      "today",
      "within 24 hours",
      "within 24 hrs",
      "expires today",
      "expire today",
      "last chance",
      "hurry",
      "limited time",
      "limited period",
      "only today",
      "don't delay",
      "do not delay",
      "by tomorrow",
      "expires in",
      "time limit",
      "pay now",
    ],
    explanation:
      "The message pressures you to act immediately or before a short deadline, leaving no time to verify.",
  },
  {
    id: "credential_request",
    category: "credential_request",
    severity: "high",
    title: "Credential request",
    phrases: [
      "otp",
      "one time password",
      "one-time password",
      "verification code",
      "verify code",
      "authentication code",
      "password",
      "passcode",
      "secret code",
      "pin",
      "upi pin",
      "mpin",
      "cvv",
      "cvv2",
      "atm pin",
      "login credentials",
      "card number",
      "card details",
      "account number",
      "expiry date",
      "2fa code",
      "share your otp",
      "send your otp",
      "enter the otp",
      "bank details",
    ],
    explanation:
      "The message requests a sensitive authentication credential or account detail — information only you and your bank should know.",
  },
  {
    id: "financial_request",
    category: "financial_request",
    severity: "high",
    title: "Financial request",
    phrases: [
      "send money",
      "money transfer",
      "wire transfer",
      "transfer",
      "transferred",
      "payment",
      "kindly pay",
      "confirm payment",
      "pay",
      "upi",
      "gpay",
      "phonepe",
      "fee",
      "fees",
      "deposit",
      "refund",
      "refunds",
      "invest",
      "investment",
      "double your money",
      "guaranteed returns",
      "registration fee",
      "processing fee",
      "customs fee",
      "recharge",
    ],
    explanation:
      "The message asks for money, a payment, a transfer, or a financial commitment — a core pattern in payment fraud.",
  },
  {
    id: "impersonation",
    category: "impersonation",
    severity: "high",
    title: "Trusted-entity impersonation",
    phrases: [
      "bank",
      "your bank",
      "state bank",
      "sbi",
      "hdfc",
      "icici",
      "axis bank",
      "kotak",
      "customer care",
      "customer support",
      "support",
      "support team",
      "representative",
      "government",
      "govt",
      "income tax",
      "tax department",
      "rbi",
      "police",
      "cyber cell",
      "kyc",
      "delivery",
      "courier",
      "postman",
      "parcel",
      "helpline",
      "nodal officer",
      "hr team",
      "recruitment team",
    ],
    explanation:
      "The message borrows the identity of a trusted bank, government body, police, delivery service, or support team to gain your trust.",
  },
  {
    id: "reward_lure",
    category: "reward_lure",
    severity: "medium",
    title: "Reward or lure",
    phrases: [
      "congratulations",
      "you have won",
      "you've won",
      "lottery",
      "prize",
      "prizes",
      "winner",
      "winners",
      "cashback",
      "free gift",
      "lucky draw",
      "giveaway",
      "selected for",
      "exclusive offer",
      "guaranteed income",
      "risk-free",
      "claim your reward",
      "reward",
    ],
    explanation:
      "The message dangles a prize, lottery, cashback, or guaranteed return — a classic bait to lower your guard.",
  },
  {
    id: "threat",
    category: "threat",
    severity: "high",
    title: "Account or legal threat",
    phrases: [
      "account blocked",
      "account will be blocked",
      "account suspended",
      "account will be suspended",
      "will be suspended",
      "permanent suspension",
      "permanently blocked",
      "legal action",
      "penalty",
      "penalties",
      "police case",
      "case filed",
      "deactivated",
      "terminate your account",
      "close your account",
      "blacklisted",
    ],
    explanation:
      "The message threatens account blocking, suspension, legal action, or penalties to frighten you into compliance.",
  },
];
